version: '3'

services:

    app:
      image: rpopuc/php-fpm-nginx:8.0
      volumes:
        - ./:/var/www/

    postgres:
      image: rpopuc/postgres:13
      volumes:
        - ./.docker/data/postgres:/var/lib/postgresql/data
